trento-project/ansible

- README.md
- roles/containers/tasks/main.yml
- roles/proxy/templates/trento.conf.j2
Some minor improvements that might help:
- note about using proper IP for rabbitmq based on network congif
- note about api-key not being supported yet, so better disable it to get a functional deployment
- always pull images to get the latest version among playbook reruns
- minor fix in nginx config template to avoid double slashes `//grafana`
> Improve doc

- README.md
- playbook.cleanup.yml
- roles/containers/defaults/main.yml
- roles/containers/tasks/main.yml
- roles/rabbitmq/defaults/main.yml
- roles/rabbitmq/tasks/cleanup.yml
- roles/rabbitmq/tasks/main.yml
Clean up rabbitmq vhost (which now is configurable). Once the vhost is cleaned up all the exchanges/queues are gone.
Using vhosts enables us to have completely independent environments using the same exchange names: https://www.rabbitmq.com/vhosts.html
The amqp connection string vhost part must be encoded (urlencode doesn't replace `/`... https://jinja.palletsprojects.com/en/2.11.x/templates/#urlencode).
Anyway, we should maybe encourage the creation of vhosts without trailling `/`...
> Cleanup rabbitmq

- README.md
- roles/containers/defaults/main.yml
- roles/containers/tasks/cleanup.yml
Remove web and wanda container images optionally, removing them being the default behaviour.
This enables the cleanup usage in the PR environment creation, as we don't want to remove wanda image as it uses a fixed tag
> Remove container images optionally during cleanup

- .github/workflows/ci.yaml
Upload the current playbook tarball on releases.
With this, the project will start having a rolling release, and everytime we release officially, the code will be frozen for that commit.
> Upload current code tarball to releases

- playbook.yml
- roles/prometheus/tasks/main.yml
This PR adds:
- A check in the pre_tasks of the playbook. The check will prevent the execution on distributions others than SLES for SAP 15 SP3, SP4 or SP5
- A conditional that executes the `expect` workaround that manually installs the user/group for prometheus. This conditional will ensure that the workaround is only executed when needed (SP4 and SP5)
- Changes yaml formatting for the playbook so that we use 2 spaces for indentation. I've seen this in most of YAML guidelines and my formatter follows this also. I can remove it if we prefer to stay with 1-space.
I've checked the logic in all 3 supported targets and it works as expected
> Add distribution detection logic

- .ansible-lint
- .yamllint
- playbook.cleanup.yml
- playbook.yml
- roles/agent/handlers/main.yml
- roles/agent/tasks/main.yml
- roles/containers/tasks/main.yml
- roles/postgres/handlers/main.yml
- roles/postgres/tasks/cleanup.yml
- roles/postgres/tasks/main.yml
- roles/proxy/handlers/main.yml
- roles/rabbitmq/tasks/main.yml
This PR adds a .yamllint that will be enforced by the `ansible-lint` in the CI. We set it to 2 space indentation but it also applies some default like long lines checks. The code has been adjusted to meet this rules.
> Add indent rule yamllint

- README.md
- roles/containers/defaults/main.yml
- roles/containers/tasks/main.yml
This PR makes use of the env var added in https://github.com/trento-project/web/pull/2147 to disable the usage of the new charts feature by introducing the `enable_charts` var. The variable has a default value of `true` (it shouldn't be necessary to set it true as it's already `true` by default in `trento-web` but I think it helps to make it more obvious)
@CDimonaco something I noticed is that you used `CHARTS_ENABLED` for the env var, where we usually use the form `ENABLE_<something>` for such things, if it's ok by you, could we change this for uniformity?
> Allow charts to be optional when deploying trento-web

- playbook.cleanup.yml
- playbook.yml
- roles/prometheus/handlers/main.yml
- roles/prometheus/tasks/cleanup.yml
- roles/prometheus/tasks/main.yml
- roles/proxy/tasks/cleanup.yml
- roles/proxy/tasks/main.yml
This PR will prevent the firewalld exceptions from being applied  / removed when the firewalld service is not active, as this would cause the playbook execution to fail.
> Only apply firewalld exceptions when firewalld is running

- roles/proxy/templates/trento.conf.j2
This temporary fixes the issues with https ad websockets in trento web.
It injects an empty origin to bypass the phoenix websocket origin checking.
This is a temporary workaround
> Temporary HTTPS Fix 

- roles/containers/tasks/main.yml
A small follow-up PR to improve the fail and success msg in the role containers tasks in the "Verify that alerting configuration ..." step
Thanks to @CDimonaco for pointing out :+1:  that json configuration may not be the correct naming. Changed to playbook variables.
> Improve log message for verify alerting env's step

- README.md
- roles/agent/defaults/main.yml
- roles/agent/tasks/main.yml
- roles/proxy/defaults/main.yml
Fix a couple of default values and usages:
- `nginx_vhost_filename`, it was not updated from `nginx_conf_filename`
- `rabbitmq_vhost value` in agent side
> Fix nginx_vhost_filename and rabbitmq_vhost usage

- roles/postgres/tasks/main.yml
This PR includes a workaround to allow the installation of the postgres role in azure-based SLES 15 SP3 installations.
For a bit of context: our azure SLES images are built using core packages newer than what's usually available in the SLES 15 SP3 repos, causing that some packages that don't come preinstalled show conflicts during the installation. This workaround will be able to force the installation under such circumstances while still allow a regular SP3 installation to work.
> Workaround to allow installation with newer ncurses

- .github/workflows/ci.yaml
This PR adds some basic testing for the playbooks, using the RPM installation method in
- SP3
- SP4
- SP5
It: 
- Runs `playbook.yml`
- Does a simple curl test to the readyness endpoint (`/api/readyz`
- Runs `playbook.cleanup.yml`
3 new machines have been deployed in azure for this purpose. I'm currently adding the required variables to the repository secrets
> Add RPM tests for SP3, SP4, SP5

- README.md
- Move the variable notes closer to the relevant section
- Add clarification about the `@` in the `--extra-vars` argument.
> Improve notes

- roles/app/tasks/docker.yml
- roles/app/templates/trento-web.j2
- roles/proxy/templates/trento.conf.j2
This PR makes use of the en var added in https://github.com/trento-project/web/pull/2671
Setting to draft until:
- merge freeze is over
- the menitoned PR is merged
> Make use of the new TRENTO_DOMAIN env var required for WSS

- roles/app/tasks/docker.yml
- roles/app/templates/trento-web.j2
Just a tiny fix. Please confirm I did not forget anything 😄
> Rename `TRENTO_DOMAIN` to `TRENTO_WEB_ORIGIN`

- .github/workflows/ci.yaml
This pr enables building arm64 docker images.
> Docker image building for arm64

- .github/workflows/ci.yaml
This PR allows the cleanup playbook to be executed regardless if the deployment playbook finishes successfully or not. 
The playbooks are tested in persistent machines running in the cloud and when a deployment run doesn't finish successfully, the machine is left in an undetermined state that might affect the execution of the next CI run. This PR:
- Separates the cleanup in a separate job to see more clearly if it executed correctly
- Adds a continue-on-error: true to the deployment playbook so that the clean playbook still gets executed if it fails
> Allow cleanup(test) to run regardless of deployment

- README.md
- roles/app/defaults/main.yml
- roles/app/tasks/docker.yml
- roles/app/templates/trento-web.j2
As title suggest, this pr adds the oidc configuration parameters for trent-web project
> Add oidc configuration params

- .github/workflows/ci.yaml
- README.md
- docker/Dockerfile
- roles/app/defaults/docker.yml
- roles/app/tasks/docker.yml
- roles/app/tasks/docker_cleanup.yml
Add missing checks during a docker based installation.
Note: the pipeline currently tests the playbook in rpm mode, and it would be great testing also the docker mode.
Options are:
- after the rpm test we run docker tests on the same machines, meaning the pipeline would take longer
- we have a set of other 3 machines to concurrently test also docker installation
Open for suggestions.
> Deploy checks in docker mode

- .github/workflows/ci.yaml
- README.md
- Vagrantfile
- examples/dedicated-nodes/README.md
- examples/dedicated-nodes/inventory.yml
- examples/external-services/README.md
- examples/external-services/inventory.yml
- examples/single-node/README.md
- examples/single-node/inventory.yml
- playbook.cleanup.yml
- playbook.yml
As per the [Ansible docs](https://docs.ansible.com/ansible/latest/network/getting_started/first_inventory.html):
> Avoid spaces, hyphens, and preceding numbers (use floor_19, not 19th_floor) in your group names. Group names are case sensitive.
This PR replaces every `-` with `_` in inventory group names. These changes have no functional effect but increase the portability of the playbook (some Ansible installation are less permissive and may reject the inventory).
> Use underscores in inventory host groups

- .gitignore
- scripts/make_single_node.sh
Add a script to help set up a new execution of the playbook. The script is meant to help the development, and it only supports the single-node scenario so far. 
The script:
* Creates a self-signed certificate and private key for the given host (will be used by the nginx proxy)
* Compose a variable JSON file
* Compose an inventory YAML file
* Compose an inventory INI file
* Output the command to execute to run the playbook
By default, it puts the files in the `./data` directory, which is ignored by git.
Depends on #49
> Add development script

- .ansible-lint
- .github/workflows/ci.yaml
- .yamllint
- examples/dedicated-nodes/inventory.yml
- examples/external-services/inventory.yml
- examples/install-agents/inventory.yml
- examples/single-node/inventory.yml
- roles/postgres/defaults/main.yml
- roles/postgres/tasks/cleanup.yml
- roles/postgres/tasks/main.yml
- roles/postgres/vars/main.yml
- roles/prometheus/defaults/main.yml
Update the ansible-linter action in the CI to the latest version of v25.
To accomodate the new rules:
- In Postgres role fixed `partial_become` definitions by combining `become` and `become_user` together in task block. Moved the previously independent tasks under the newly created task groups.
- Added `---` marker to all yaml files that were missing it;
- Added var-naming[no-role-prefix] as exception rule in the linter, temporarily to not block progress on the repository. 
The `no-role-prefix` would be removed once gradually fixing all the places it is encountered. This will involve a backwards-compatibility and alot of changes, so will be addressed in separete PR.
> Updated ansible linter in the CI to v25
